spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whiskey
    username: root
    password: 'R@simgunay2018'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 1221